# American Housing Survey Project

Explore year 2013 of national and metro datasets from the [Housing Affordability Data System (HADS)](https://www.huduser.gov/portal/datasets/hads/hads.html) data source.

In [1]:
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from urllib.request import urlopen
from zipfile import ZipFile
from io import BytesIO

%matplotlib inline

### Read data

In [2]:
# Read Natinal Data 
national_url = 'https://www.huduser.gov/portal/datasets/hads/hads2013n_ASCII.zip'
national_file = 'thads2013n.txt'

z_national = urlopen(national_url)
zip_national = ZipFile(BytesIO(z_national.read())).extract(national_file)
df_national = pd.read_csv(zip_national)

In [3]:
df_national.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64535 entries, 0 to 64534
Data columns (total 99 columns):
CONTROL                64535 non-null object
AGE1                   64535 non-null int64
METRO3                 64535 non-null object
REGION                 64535 non-null object
LMED                   64535 non-null int64
FMR                    64535 non-null int64
L30                    64535 non-null int64
L50                    64535 non-null int64
L80                    64535 non-null int64
IPOV                   64535 non-null int64
BEDRMS                 64535 non-null int64
BUILT                  64535 non-null int64
STATUS                 64535 non-null object
TYPE                   64535 non-null int64
VALUE                  64535 non-null int64
VACANCY                64535 non-null int64
TENURE                 64535 non-null object
NUNITS                 64535 non-null int64
ROOMS                  64535 non-null int64
WEIGHT                 64535 non-null float64
PER                    64535 non-null int64
ZINC2                  64535 non-null int64
ZADEQ                  64535 non-null object
ZSMHC                  64535 non-null int64
STRUCTURETYPE          64535 non-null int64
OWNRENT                64535 non-null object
UTILITY                64535 non-null float64
OTHERCOST              64535 non-null float64
COST06                 64535 non-null float64
COST12                 64535 non-null float64
COST08                 64535 non-null float64
COSTMED                64535 non-null float64
TOTSAL                 64535 non-null int64
ASSISTED               64535 non-null int64
GLMED                  64535 non-null int64
GL30                   64535 non-null int64
GL50                   64535 non-null int64
GL80                   64535 non-null int64
APLMED                 64535 non-null float64
ABL30                  64535 non-null float64
ABL50                  64535 non-null float64
ABL80                  64535 non-null float64
ABLMED                 64535 non-null float64
BURDEN                 64535 non-null float64
INCRELAMIPCT           64535 non-null float64
INCRELAMICAT           64535 non-null int64
INCRELPOVPCT           64535 non-null float64
INCRELPOVCAT           64535 non-null int64
INCRELFMRPCT           64535 non-null float64
INCRELFMRCAT           64535 non-null int64
COST06RELAMIPCT        64535 non-null float64
COST06RELAMICAT        64535 non-null int64
COST06RELPOVPCT        64535 non-null float64
COST06RELPOVCAT        64535 non-null int64
COST06RELFMRPCT        64535 non-null float64
COST06RELFMRCAT        64535 non-null int64
COST08RELAMIPCT        64535 non-null float64
COST08RELAMICAT        64535 non-null int64
COST08RELPOVPCT        64535 non-null float64
COST08RELPOVCAT        64535 non-null int64
COST08RELFMRPCT        64535 non-null float64
COST08RELFMRCAT        64535 non-null int64
COST12RELAMIPCT        64535 non-null float64
COST12RELAMICAT        64535 non-null int64
COST12RELPOVPCT        64535 non-null float64
COST12RELPOVCAT        64535 non-null int64
COST12RELFMRPCT        64535 non-null float64
COST12RELFMRCAT        64535 non-null int64
COSTMedRELAMIPCT       64535 non-null float64
COSTMedRELAMICAT       64535 non-null int64
COSTMedRELPOVPCT       64535 non-null float64
COSTMedRELPOVCAT       64535 non-null int64
COSTMedRELFMRPCT       64535 non-null float64
COSTMedRELFMRCAT       64535 non-null int64
FMTZADEQ               64535 non-null object
FMTMETRO3              64535 non-null object
FMTBUILT               64535 non-null object
FMTSTRUCTURETYPE       64535 non-null object
FMTBEDRMS              64535 non-null object
FMTOWNRENT             64535 non-null object
FMTCOST06RELPOVCAT     64535 non-null object
FMTCOST08RELPOVCAT     64535 non-null object
FMTCOST12RELPOVCAT     64535 non-null object
FMTCOSTMEDRELPOVCAT    64535 non-null object
FMTINCRELPOVCAT        64535 non-null object
FMTCOST06RELFMRCAT     64535 non-null object
FMTCOST08RELFMRCAT     64535 non-null object
FMTCOST12RELFMRCAT     64535 non-null object
FMTCOSTMEDRELFMRCAT    64535 non-null object
FMTINCRELFMRCAT        64535 non-null object
FMTCOST06RELAMICAT     64535 non-null object
FMTCOST08RELAMICAT     64535 non-null object
FMTCOST12RELAMICAT     64535 non-null object
FMTCOSTMEDRELAMICAT    64535 non-null object
FMTINCRELAMICAT        64535 non-null object
FMTASSISTED            64535 non-null object
FMTBURDEN              64535 non-null object
FMTREGION              64535 non-null object
FMTSTATUS              64535 non-null object
dtypes: float64(28), int64(39), object(32)
memory usage: 48.7+ MB

In [4]:
df_national.head()

,CONTROL,AGE1,METRO3,REGION,LMED,FMR,L30,L50,L80,IPOV,...,FMTINCRELFMRCAT,FMTCOST06RELAMICAT,FMTCOST08RELAMICAT,FMTCOST12RELAMICAT,FMTCOSTMEDRELAMICAT,FMTINCRELAMICAT,FMTASSISTED,FMTBURDEN,FMTREGION,FMTSTATUS
0,'100003130103',82,'3','1',73738,956,15738,26213,40322,11067,...,'1 LTE 50% FMR','2 30 - 50% AMI','2 30 - 50% AMI','2 30 - 50% AMI','2 30 - 50% AMI','2 30 - 50% AMI','.','2 30% to 50%','-5','-5'
1,'100006110249',50,'5','3',55846,1100,17165,28604,45744,24218,...,'3 GT FMR','4 60 - 80% AMI','4 60 - 80% AMI','6 100 - 120% AMI','4 60 - 80% AMI','7 120% AMI +','.','1 Less than 30%','-5','-5'
2,'100006370140',53,'5','3',55846,1100,13750,22897,36614,15470,...,'2 50.1 - 100% FMR','4 60 - 80% AMI','5 80 - 100% AMI','6 100 - 120% AMI','4 60 - 80% AMI','4 60 - 80% AMI','.','3 50% or More','-5','-5'
3,'100006520140',67,'5','3',55846,949,13750,22897,36614,13964,...,'2 50.1 - 100% FMR','6 100 - 120% AMI','7 120% AMI +','7 120% AMI +','5 80 - 100% AMI','4 60 - 80% AMI','.','1 Less than 30%','-5','-5'
4,'100007130148',26,'1','3',60991,737,14801,24628,39421,15492,...,'3 GT FMR','3 50 - 60% AMI','3 50 - 60% AMI','3 50 - 60% AMI','3 50 - 60% AMI','7 120% AMI +','0 Not Assisted','1 Less than 30%','-5','-5'